module.exports =[
  { "country": "Afghanistan", "code": "AF" },
  { "country": "Albania", "code": "AL" },
  { "country": "Algeria", "code": "DZ" },
  { "country": "Andorra", "code": "AD" },
  { "country": "Angola", "code": "AO" },
  { "country": "Antigua and Barbuda", "code": "AG" },
  { "country": "Argentina", "code": "AR" },
  { "country": "Armenia", "code": "AM" },
  { "country": "Australia", "code": "AU" },
  { "country": "Austria", "code": "AT" },
  { "country": "Azerbaijan", "code": "AZ" },
  { "country": "Bahamas", "code": "BS" },
  { "country": "Bahrain", "code": "BH" },
  { "country": "Bangladesh", "code": "BD" },
  { "country": "Barbados", "code": "BB" },
  { "country": "Belarus", "code": "BY" },
  { "country": "Belgium", "code": "BE" },
  { "country": "Belize", "code": "BZ" },
  { "country": "Benin", "code": "BJ" },
  { "country": "Bhutan", "code": "BT" },
  { "country": "Bolivia", "code": "BO" },
  { "country": "Bosnia and Herzegovina", "code": "BA" },
  { "country": "Botswana", "code": "BW" },
  { "country": "Brazil", "code": "BR" },
  { "country": "Brunei", "code": "BN" },
  { "country": "Bulgaria", "code": "BG" },
  { "country": "Burkina Faso", "code": "BF" },
  { "country": "Burundi", "code": "BI" }
]
